const { chromium } = await import(process.env.SALER_PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173');await page.evaluate(()=>document.fonts.ready);
const images=await page.evaluate(async()=>Promise.all(COINS.map(c=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve({id:c.id,loaded:img.naturalWidth>0,width:img.naturalWidth,height:img.naturalHeight});img.onerror=()=>resolve({id:c.id,loaded:false});img.src=c.image;}))));
assert.equal(images.length,20);assert.ok(images.every(i=>i.loaded),'All 20 local coin images must decode successfully');
assert.equal(await page.locator('.coin-card .coin-image').count(),6);
assert.equal(await page.locator('.coin-card .coin-image[alt="Pepe logo"]').count(),1);
assert.equal(await page.locator('.coin-card .coin-image[alt="dogwifhat logo"]').count(),1);
await page.locator('.cards').screenshot({path:'/tmp/saler-real-coin-images.png'});
assert.ok((await page.locator('.activity-rail').textContent()).includes('User #999'));
assert.ok((await page.locator('.activity-rail').textContent()).includes('claimed $8 from Shiba Inu'));
assert.ok(!/\bexample\b/i.test(await page.locator('.activity-rail').textContent()));
const guestBalance=await page.evaluate(()=>totals().available);
await page.locator('.rail-heading a').click();await page.getByText('COMMUNITY CASHBACK.',{exact:true}).waitFor({state:'visible'});assert.ok(await page.getByText('COMMUNITY CASHBACK.',{exact:true}).isVisible());
assert.equal(await page.locator('#community-content .community-claim').count(),12);
assert.ok((await page.locator('#community-content').textContent()).includes('User #999'));
await page.locator('[data-community-page="2"]').click();assert.equal(await page.locator('#community-content .community-claim').count(),12);assert.ok(!(await page.locator('#community-content').textContent()).includes('User #999'));
assert.equal(await page.evaluate(()=>totals().available),guestBalance,'Community claims must not affect the visitor balance');
await page.goto('http://127.0.0.1:4173');
await page.screenshot({path:'/tmp/saler-desktop.png',fullPage:true});
assert.equal(await page.locator('.coin-card').count(),6);
await page.locator('#coin-search').fill('pepe');assert.equal(await page.locator('.coin-card').count(),1);
await page.locator('#coin-search').fill('nothing-matches');assert.equal(await page.locator('.coin-card').count(),0);
await page.getByRole('button',{name:'Reset filters',exact:true}).click();
await page.locator('[data-category="Cats"]').click();assert.equal(await page.locator('.coin-card').count(),5);
await page.locator('[data-category="All"]').click();await page.getByRole('button',{name:'Page 2',exact:true}).click();assert.equal(await page.locator('.coin-card').count(),6);
await page.goto('http://127.0.0.1:4173/#/coin/dogecoin');
await page.locator('[data-save]').click();await page.reload();assert.equal(await page.locator('[data-save]').getAttribute('aria-pressed'),'true');
const before=await page.evaluate(()=>totals().available);
await page.locator('#purchase-amount').fill('100');await page.locator('#purchase-form input[type=checkbox]').check();await page.locator('#purchase-form button[type=submit]').click();
assert.equal(await page.evaluate(()=>state.purchases[0].status),'ineligible');assert.equal(await page.evaluate(()=>totals().available),before);
await page.locator('#purchase-amount').fill('200');await page.locator('#purchase-form input[type=checkbox]').check();await page.locator('#purchase-form button[type=submit]').click();assert.equal(await page.evaluate(()=>totals().available),before+6);
await page.locator('#purchase-status').selectOption('pending');await page.locator('#purchase-form input[type=checkbox]').check();await page.locator('#purchase-form button[type=submit]').click();assert.equal(await page.evaluate(()=>state.purchases[0].status),'pending');assert.equal(await page.evaluate(()=>totals().available),before+6);
await page.goto('http://127.0.0.1:4173/#/activity');await page.locator('[data-approve]').click();assert.equal(await page.evaluate(()=>totals().available),before+12);
await page.goto('http://127.0.0.1:4173/#/coin/pepe');await page.locator('#purchase-status').selectOption('failed');await page.locator('#purchase-form input[type=checkbox]').check();await page.locator('#purchase-form button[type=submit]').click();assert.equal(await page.evaluate(()=>state.purchases[0].cashback),0);
await page.goto('http://127.0.0.1:4173/#/rewards');await page.locator('[data-redeem="amazon"]').click();await page.locator('#redeem-email').fill('test@example.com');await page.locator('#redeem-form input[type=checkbox]').check();await page.locator('#redeem-form button').click();assert.equal(await page.evaluate(()=>state.redemptions.length),1);assert.equal(await page.evaluate(()=>totals().available),before+2);assert.equal(await page.locator('#dialog').getAttribute('open'),'');await page.locator('#dialog-close').click();
await page.goto('http://127.0.0.1:4173/#/settings');await page.locator('#pref-name').fill('Tester');await page.locator('#settings-form button').click();await page.reload();assert.equal(await page.locator('#pref-name').inputValue(),'Tester');
await page.locator('#reset-local').click();await page.locator('#confirm-reset').click();assert.equal(await page.evaluate(()=>state.purchases.length),0);assert.equal(await page.evaluate(()=>state.redemptions.length),0);assert.equal(await page.evaluate(()=>totals().available),before);
assert.equal(before,0,'Seeded sample activity must not create a real account balance');
await page.goto('http://127.0.0.1:4173');assert.ok((await page.locator('#header-balance').textContent()).includes('Register and get your first $10 to spend'));
assert.ok((await page.locator('.balance-card').textContent()).includes('Register and get your first $10 to spend'));
assert.ok((await page.locator('.hero-copy').textContent()).includes('3–10% cashback'));
assert.ok((await page.locator('.hero-copy').textContent()).includes('over $100'));
assert.ok((await page.locator('.hero-copy').textContent()).includes('gift cards'));
await page.locator('#header-account-action').click();await page.locator('#register-name').fill('Reward Tester');await page.locator('#register-email').fill('welcome@example.com');await page.locator('#register-form input[type=checkbox]').check();await page.locator('#register-form button').click();
assert.equal(await page.evaluate(()=>totals().available),10);await page.reload();assert.equal(await page.evaluate(()=>totals().welcomeCredit),10);assert.equal(await page.locator('#header-account-action').textContent(),'My cashback');
await page.evaluate(()=>registerDialog());assert.equal(await page.evaluate(()=>totals().available),10,'Registering again must not duplicate credit');
for(const [coin,rate,cashback] of [['dogwifhat',7,14],['pepe',8,16],['pudgy-penguins',10,20]]){
await page.goto('http://127.0.0.1:4173/#/coin/'+coin);assert.ok((await page.locator('#purchase-hint').textContent()).includes(rate+'%'));assert.ok((await page.locator('#purchase-cashback').textContent()).includes('$'+cashback+'.00'));
await page.locator('#purchase-form input[type=checkbox]').check();await page.locator('#purchase-form button[type=submit]').click();assert.equal(await page.evaluate(()=>state.purchases[0].rate),rate);assert.equal(await page.evaluate(()=>state.purchases[0].cashback),cashback);
}
assert.equal(await page.evaluate(()=>totals().available),60);
await page.goto('http://127.0.0.1:4173');await page.locator('#calc-coin').selectOption('pepe');assert.equal(await page.locator('#calc-result').textContent(),'$40.00');await page.locator('#calc-coin').selectOption('dogwifhat');assert.equal(await page.locator('#calc-result').textContent(),'$35.00');await page.locator('#calc-amount').fill('100');assert.equal(await page.locator('#calc-result').textContent(),'$0.00');
await page.locator('#coin-search').fill('pepe');assert.equal(await page.locator('.coin-bottom strong').textContent(),'8% cashback');await page.locator('#coin-search').fill('dogwifhat');assert.equal(await page.locator('.coin-bottom strong').textContent(),'7% cashback');
await page.goto('http://127.0.0.1:4173/#/settings');await page.locator('#reset-local').click();await page.locator('#confirm-reset').click();assert.equal(await page.evaluate(()=>state.account),null);assert.equal(await page.evaluate(()=>totals().available),0);
await page.goto('http://127.0.0.1:4173/#/coin/missing');assert.ok(await page.getByText('COIN NOT FOUND.').isVisible());
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});for(const route of ['/', '/explore','/coin/dogecoin','/portfolio','/rewards','/activity','/community','/settings']){await page.goto('http://127.0.0.1:4173/#'+route);const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(dimensions.scroll<=dimensions.viewport+1,`overflow at ${width} ${route}: ${JSON.stringify(dimensions)}`);assert.ok(!/interactive prototype|\bsimulat(?:e|ed|ion)|\bdemo\b|\bexample\b/i.test(await page.locator('#app').innerText()),`Technical wording in main view ${route}`)} }
await page.goto('http://127.0.0.1:4173/#/terms');assert.ok((await page.locator('#app').innerText()).includes('No real trading, payments'));
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4173');await page.screenshot({path:'/tmp/saler-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: community cashback claims and pagination without changing personal balance, clear narrative, Terms, all 20 real coin images, registration, one-time $10 credit, coin rates, calculator, search, filters, detail links, saved coins, purchase states, rewards, preferences, reset, and 32 responsive route checks.');await browser.close();
